{
 "title": "Jira Sprint Summary",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "board_id",
    "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn:(r) => r._measurement == \"jira\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> distinct(column: \"board_id\")"
   },
   {
    "name": "sprint_id",
    "label": "sprint_id",
    "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn:(r) => r._measurement == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> distinct(column: \"sprint_id\")"
   },
   {
    "name": "project_key",
    "label": "project_key",
    "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn:(r) => r._measurement == \"jira\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> distinct(column: \"project_key\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Task on Sprint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> group()\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Work progress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nq1 = from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> group(columns: [\"sprint_id\"], mode:\"by\")\n  |> count()\n\nq2 = from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"42\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"27\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => r[\"_value\"] == \"Done\")\n  |> group(columns: [\"sprint_id\"], mode:\"by\")\n  |> count()\njoin(tables: {q1: q1, q2: q2}, on: [\"sprint_id\"])\n  |> map(fn: (r) => ({_value: (float(v: r._value_q2) / float(v: r._value_q1) * 100.0)}))"
    }
   ]
  },
  {
   "title": "Total Worklog",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"worklog\")\n  |> group()\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "To Do Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => r[\"_value\"] == \"To Do\")\n  |> group()\n  |> count()"
    }
   ]
  },
  {
   "title": "In Progress Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => r[\"_value\"] == \"In Progress\")\n  |> group()\n  |> count()"
    }
   ]
  },
  {
   "title": "Done Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => r[\"_value\"] == \"Done\")\n  |> group()\n  |> count()"
    }
   ]
  },
  {
   "title": "Workload / User",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"timespent\")\n  |> group(columns: [\"assignee\"], mode:\"by\")\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Task / User",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> group(columns: [\"assignee\"], mode:\"by\")\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Worklog / User",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"worklog\")\n  |> group(columns: [\"assignee\"], mode:\"by\")\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Workload / Project",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"project_key\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"timespent\")\n  |> group(columns: [\"project_key\"], mode:\"by\")\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Task / Project",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"project_key\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> group(columns: [\"project_key\"], mode:\"by\")\n  |> count(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Worklog / Project",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"jira\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jira\")\n  |> filter(fn: (r) => r[\"board_id\"] == \"${board_id}\")\n  |> filter(fn: (r) => r[\"sprint_id\"] == \"${sprint_id}\")\n  |> filter(fn: (r) => r[\"project_key\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"worklog\")\n  |> group(columns: [\"project_key\"], mode:\"by\")\n  |> sum(column: \"_value\")"
    }
   ]
  }
 ]
}